version: '3.8'

services:

  mysql:
    container_name: oa-mysql
    build: ./mysql
    ports:
      - "33060:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234

  redis:
    container_name: oa-redis
    build: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
  
  php:
    container_name: oa-php
    build: ./php
    working_dir: /var/www
    depends_on:
      - mysql
      - redis
    links:
      - "mysql:mysql"
      - "redis:redis"
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www
      - ./php/config:/etc/apache2/sites-enabled
  
  # jenkins:
  #   container_name: oa-jenkins
  #   build: ./jenkins
  #   ports:
  #     - "8081:8080"
  #     - "50000:50000"
  #   volumes:
  #     - ./jenkins/data:/var/jenkins_home
  #     - /var/run/docker.sock:/var/run/docker.sock
